# Default values for collector-clair.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

rodeHost: "rode:50051"

debug: false

image:
  repository: "ghcr.io/rode/collector-clair"
  tag: ""
  pullPolicy: IfNotPresent

extraEnv: []

container:
  port: 8081
service:
  type: ClusterIP
  port: 8081

tolerations: []
affinity: {}
podLabels: {}
nodeSelector: {}
podAnnotations: {}

replicaCount: 1

resources:
  limits:
    cpu: 128m
    memory: 64Mi
  requests:
    cpu: 64m
    memory: 32Mi

