name: test

on:
  push:
    branches:
      - "*"
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container: golang:1.15
    steps:
      - uses: actions/checkout@v2

      - name: Download Dependencies
        run: go mod tidy

      - name: Build
        run: go build -v .

      - name: CodeCov
        run: |
          bash -c '/bin/bash <(curl -s https://codecov.io/bash)'


